name: Deploy to GitHub Pages

on:
  # Lance le workflow à chaque push sur la branche "main"
  push:
    branches: [ "main" ]
  # Vous permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Autorise un seul déploiement concurrentiel à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Charger le contenu depuis la racine du dépôt
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
